### ISSUE TITLE
Refactor Modbat.exploreSuccessor

### ISSUE THREAD

**Issue by cyrille-artho** [cyrille-artho/modbat#16]
Divide it into smaller functions.

**Comment by wruiwr** [comment]
@cyrille-artho I have merged issue-16 from issue-69 where the user-defined search function is not enabled by default setting in configuration. I have tested path coverage for issue-16 after merging with issue-69, so I think issue-16 can be merged into master now if it is fine after you check it.   For issue-69, there's still the problem with user-defined function but I will try to fix that branch later.

**Comment by cyrille-artho** [comment]
Were you able to automate the human input by providing a mock?

**Comment by wruiwr** [comment]
Currently, issue-16 can do automated test by using test.sh for path coverage except for the feature involving the human input for the search function (not enabled by default setting).
It means only the search function have not been tested. Currently I don't quite understand how mock works but I will see how I can provide a mock for the issue-69. After fixing issue-69, the search function can be enabled and tested by using --bfsearch-Fun according to the code in configuration.scala. Anyway, issue-16 is fine to merge with master for now I think.

**Comment by cyrille-artho** [comment]
I think the easiest way to experiment with mocking is to write a simple test program that uses stdin. The mock can then replace each call to "input" with a predetermined results. You can set up the mock such that it returns "quit" a predefined number of times, and after that, something else.
I'll try to merge issue-16.

**Comment by wruiwr** [comment]
If I understood right, It seems the idea of the mock is to use predefined results to replace "input" values from the user for readLine(). But we don't know what value is the "input" from the user for the readLine(), so the predefined results for mocking are only for testing, such as "quit" ? When users use the tool, they still need to give an input value for the readLine()  right?

**Comment by cyrille-artho** [comment]
Yes, a mock is a fake object that replaces a real component during testing: https://en.wikipedia.org/wiki/Mock_object
The motivation for this can be that the real component is not available, or test automation.

**Comment by cyrille-artho** [comment]
I merged issue-16 now with master. May I close (delete) this branch?

**Comment by wruiwr** [comment]
Yeah, ok, it is fine to close.  The mock thing can be fixed by branch issue-69.
