### ISSUE TITLE
Refactor `System.exit` into return codes or exceptions

### ISSUE THREAD

**Issue by cyrille-artho** [cyrille-artho/modbat#27]
For being able to use a unit-test framework on some system tests, failing configurations have to avoid exiting the VM. Therefore, it is essential that the use of `System.exit` is minimized.
This requires refactoring a lot of existing code:
- `main` cannot have a return value, so a different function (e.g., `run`) should provide the same functionality with a return value instead of exit code. `main` continues to provide an exit code for system tests and production usage, calling `run` internally.
- Any usage of `System.exit` should be rewritten such that, at the top level, `run` returns the status as an exit code, and only `main` actually exits.

As of now, there are 13 instances of `System.exit` in the code base.

**Comment by cyrille-artho** [comment]
Refactored some uses in the commits shown above. 8 instances left.

**Comment by cyrille-artho** [comment]
For cases with deeply nested method calls, exceptions would be a better way of propagating error codes (as that would not require inserting "return" statements everywhere).

**Comment by cyrille-artho** [comment]
I'll review the earlier changes w.r.t. that and convert return statements to exceptions if appropriate, and will then move on to the forked repo.

**Comment by cyrille-artho** [comment]
Something was not done so well (my mistake...); check issue #45.

**Comment by AlexandreFournel** [comment]
Existing changes to change again (to use exceptions):
https://github.com/cyrille-artho/modbat/commit/14c1fe8180359e7f56ca1d53ca1f5da1cb679fa1
[ ] ConfigMgr.scala: main
[ ] ConfigMgr.scala: parseArgs incl. return type
[ ] Main.main: use of parseArgs
https://github.com/cyrille-artho/modbat/commit/03899e84fb5f4914dc15764acf793d0ed8269ec8
https://github.com/cyrille-artho/modbat/commit/24a882f3ba3d0aaeafa87e38373c49fe01d4b17a

**Comment by cyrille-artho** [comment]
Return codes left: ConfigMgr.scala (both 0 and 1): replace "return 1" with exception, remove "return 0", and make "run" have no return parameters; Main.scala: replace "return 1" with exceptions.

**Comment by cyrille-artho** [comment]
System.exit: a couple left; try:
`find . -name '*.scala' | xargs grep 'System.exit'

**Comment by cyrille-artho** [comment]
Remaining open points:
- Modbat.explore should not have return code
- Main.run should not have return code
- Main.main should not not use return code of run (perhaps pending in a current PR?)
