### ISSUE TITLE
Document new feature about path coverage, increment minor version number

### ISSUE THREAD

**Issue by cyrille-artho** [cyrille-artho/modbat#70]
The new feature for path coverage should be automatically tested (issue #69) and documented.
The documentation should:

- [x] mention this feature in the README,
- [x] have more detailed information on the wiki,
- [x] include a wiki entry page.

For this, we also need to create a simple wiki entry page, stating that most features are (currently) documented in the README but will be moved to the wiki over time (issue #44).

**Comment by wruiwr** [comment]
Created a wiki before summer break. Need to move more things from Readme into Wiki.

**Comment by cyrille-artho** [comment]
Let's finish this task by listing all command line options and referring to our two papers on the wiki.

**Comment by wruiwr** [comment]
I will take a look.

**Comment by wruiwr** [comment]
I have added a page for the smartsearch:
https://github.com/cyrille-artho/modbat/wiki/Multi-objective-Search

and, I added the reference in for path coverage:
https://github.com/cyrille-artho/modbat/wiki/Visualization-for-Execution-Paths

**Comment by cyrille-artho** [comment]
Thank you very much!
