### ISSUE TITLE
Debug/line number info: Migrate from bytecode parsing to "sourcecode" library

### ISSUE THREAD

**Issue by cyrille-artho** [cyrille-artho/modbat#79]
When Modbat was originally written, Scala macros did not exist yet, so bytecode parsing was the only way to obtain file/source line information for displaying with the error trace.

Now, the "sourcecode" library can take care of this by using macros to embed this information at compile time, in some cases:
https://github.com/lihaoyi/sourcecode

To do:
- [x] Adapt the gradle-based build to use "sourcecode"
- [x] Add data structures to transitions to hold the necessary metadata
- [x] Capture source information with implicit macros in regular transitions
- [x] Capture source information with implicit macros for direct method calls
- [x] Capture source information with for annotated methods (using javassist as method registration happens in a delayed way, via reflection)
- [x] Update tests (line numbers may differ by 1)
- [x] Minimize code duplication with ASM-based bytecode visitors
- [x] Remove untested/unused features like launchAndChoiceInfo

Limitations:
- Annotated methods are looked up through reflection, thus their debug information has to come from bytecode analysis.
- Other info that is needed at compile time (Dotify, autoLabels in actionInfo)
- sourceInfo for action cannot be done via macros because actions are sometimes defined as part of a choice over actions, without a top-level transition of their own

**Comment by cyrille-artho** [comment]
In progress on branch "sourcecode".

**Comment by cyrille-artho** [comment]
Option "showChoices" seems to be untested and undocumented, was probably work in progress. Removing it would greatly reduce and simplify the functionality of SourceInfo.

**Comment by clagms** [comment]
Perhaps a solution is to allow the user to provide a label per choice. If such label is defined, modbat uses the label. Otherwise, it either uses the source code, or does nothing.
This solution would avoid most reflection, which seems brittle functionality.
With my admittedly meager experience, I've never needed the pretty printing of the code. I labeled each edge in a way that ensures easy trace-ability.

**Comment by cyrille-artho** [comment]
The choices are currently not labeled; they are given the "label" of the actual choice taken when used at runtime, and otherwise they remain unlabeled. Transition are given a label to summarize them, if no user-defined label is present.
I admit that this functionality is a bit brittle; it has to be evaluated at load time, so it has to guess from the structure of the bytecode what the label may be. Unfortunately, this code changes a lot between Scala releases, at least for now.
I will try to conclude the runtime part of assigning labels, and disable the feature of automatically guessing labels for 2.12 (or at least document that it only works for 2.11).

**Comment by cyrille-artho** [comment]
Merged into master. The patch migrates as much as possible, but some functionality requires static analysis and does not work with Scala 2.12 or later:
- Auto-generated labels;
- Line numbers in some cases (such as "anonymous" actions that are part of a choice).
However, the changes minimize the amount of bytecode parsing, and enable Modbat to work better with Scala 2.12.
